export {
  GRAPHIFY_SHARED_COMPANION_PATH_CONTRACT,
  buildCodebaseExplorationGuidanceSection,
  buildCompanionGuidance,
  buildCompanionPolicyXml,
  buildOpenCodeGuidance,
  hasGraphifyCapability,
  hasOpenspecCapability,
  hasTokensaveCapability,
  type GuidanceCapability,
  type GuidanceContext,
} from "./companion-guidance";
export {
  companionForkState,
  describeGitFailure,
  forkStateAgainst,
  gitEnvironment,
  GIT_QUERY_TIMEOUT_MS,
  isAuthenticationFailure,
  outputLines,
  resolveUpstreamTargetSync,
  resolveUpstreamTargetWith,
  runGitSync,
  stripGitProgress,
  upstreamTargetSteps,
  type CompanionForkState,
  type GitResult,
  type UpstreamTarget,
} from "./companion-git";
export {
  companionGitStatePath,
  companionGitStateRoot,
  COMPANION_SYNC_TTL_MS,
  FORK_VERDICT_TTL_MS,
  isCompanionSyncDue,
  readCachedForkRecord,
  readCompanionGitRecord,
  recordCompanionSync,
  recordForkVerdict,
  writeCompanionGitRecord,
  type CompanionForkRecord,
  type CompanionGitRecord,
} from "./companion-git-state";
export {
  cachedCompanionForkState,
  companionForkRefusal,
  COMPANION_SYNC_COMMAND,
  COMPANION_SYNC_TIMEOUT_MS,
  forkRefusalMessage,
  syncCompanionUnattended,
  unattendedSyncStalenessLines,
  type ForkGuardOptions,
  type UnattendedSyncOptions,
  type UnattendedSyncOutcome,
  type UnattendedSyncStatus,
} from "./companion-sync";
export { FRAMEWORK_NAME } from "./framework";
export {
  MATE_ENV,
  hasLaunchEnvironment,
  isManagedCompanionContext,
  readCompanionRuntimeContext,
  resolveCompanionRuntime,
  type CompanionRuntimeContext,
  type CompanionRuntimeResolution,
  type MateEnvVariable,
} from "./env";
export {
  projectionFreshness,
  projectionStalenessLines,
  type ProjectionFreshness,
} from "./freshness";
export {
  CODEBASE_EXPLORATION_MARKER,
  COMPANION_POLICY_MARKER,
  GUIDANCE_FILE_VERSION,
  parseGuidanceContent,
  validateGuidanceData,
  type GuidanceValidation,
  type MateGuidanceFile,
} from "./guidance";
export { mateInstallPath, mateVersion } from "./install";
export { buildProjectedGuidance } from "./projected-guidance";
export {
  companionFrameworkConfigPath,
  emptyCompanionPolicy,
  isCapabilityEnabled,
  readCompanionPolicy,
  type CompanionPolicy,
} from "./policy";
export {
  PROJECTION_ENV_FILE,
  PROJECTION_ENV_NAMES,
  PROJECTION_FIELDS,
  PROJECTION_STAMP_ENV_NAME,
  PROJECTION_YAML_FILE,
  computeProjectionStamp,
  parseProjectionEnv,
  parseProjectionYaml,
  projectionEnvPath,
  projectionYamlPath,
  readProjectionFile,
  renderProjectionEnv,
  renderProjectionYaml,
  resolveProjection,
  writeProjectionPair,
  type MateProjection,
  type ProjectionFile,
  type ProjectionStampInputs,
  type ResolvedProjection,
} from "./projection";
export {
  ancestorDirectories,
  findRepoLocalRegistryFileSync,
  repoLocalDirName,
  repoLocalDirPath,
  repoLocalFrameworkPath,
  repoLocalRegistryPath,
  type RepoLocalRegistryFile,
} from "./repo-local";
