import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { afterEach, describe, expect, test } from "bun:test";

import { FRAMEWORK_NAME } from "./framework";
import {
  PROJECTION_ENV_NAMES,
  PROJECTION_FIELDS,
  PROJECTION_STAMP_ENV_NAME,
  computeProjectionStamp,
  parseProjectionEnv,
  parseProjectionYaml,
  projectionEnvPath,
  projectionYamlPath,
  readProjectionFile,
  renderProjectionEnv,
  renderProjectionYaml,
  resolveProjection,
  writeProjectionPair,
  type MateProjection,
  type ProjectionFile,
} from "./projection";
import { findRepoLocalRegistryFileSync, repoLocalRegistryPath } from "./repo-local";

const tempRoots: string[] = [];

function makeTempDir(prefix: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  tempRoots.push(dir);
  return dir;
}

function writeRepoLocalRegistry(repoRoot: string, contents = "companions: []\n"): void {
  const registryPath = repoLocalRegistryPath(repoRoot);
  fs.mkdirSync(path.dirname(registryPath), { recursive: true });
  fs.writeFileSync(registryPath, contents, "utf8");
}

function projection(overrides: Partial<MateProjection> = {}): MateProjection {
  return {
    version: "0.15.5",
    companionPath: "/companions/acme",
    repositoryPath: "/repos/acme",
    repositoryId: "acme",
    wrapperBinPath: "/install/acme/wrappers/bin",
    reactDoctorBinPath: "/install/acme/node_modules/.bin/react-doctor",
    graphifyOut: "/companions/acme/.graphify/acme/graphify-out",
    ...overrides,
  };
}

const file = (overrides: Partial<MateProjection> = {}): ProjectionFile => ({
  stamp: "deadbeef",
  projection: projection(overrides),
});

afterEach(() => {
  for (const dir of tempRoots.splice(0)) fs.rmSync(dir, { recursive: true, force: true });
});

describe("projection contract", () => {
  test("carries paths only — every field is projected and no predicate is expressible", () => {
    expect(PROJECTION_FIELDS).toEqual([
      "version",
      "companionPath",
      "repositoryPath",
      "repositoryId",
      "wrapperBinPath",
      "reactDoctorBinPath",
      "graphifyOut",
    ]);
    expect(Object.keys(projection()).sort()).toEqual([...PROJECTION_FIELDS].sort());
  });

  test("maps each field to its launch environment variable", () => {
    expect(PROJECTION_ENV_NAMES).toEqual({
      version: "MATE_VERSION",
      companionPath: "MATE_ARTIFACT_PATH",
      repositoryPath: "MATE_REPO_PATH",
      repositoryId: "MATE_REPO_ID",
      wrapperBinPath: "MATE_WRAPPER_BIN_PATH",
      reactDoctorBinPath: "MATE_REACT_DOCTOR_BIN_PATH",
      graphifyOut: "GRAPHIFY_OUT",
    });
  });
});

describe("computeProjectionStamp", () => {
  const inputs = { version: "1.0.0", registryContent: "a: 1\n" };

  test("is stable for identical inputs", () => {
    expect(computeProjectionStamp(inputs)).toBe(computeProjectionStamp({ ...inputs }));
  });

  test("changes with the mate version and with the repo-local registry", () => {
    const base = computeProjectionStamp(inputs);
    expect(computeProjectionStamp({ ...inputs, version: "1.0.1" })).not.toBe(base);
    expect(computeProjectionStamp({ ...inputs, registryContent: "a: 2\n" })).not.toBe(base);
  });

  test("does not separate its inputs ambiguously", () => {
    expect(computeProjectionStamp({ version: "ab", registryContent: "d" })).not.toBe(
      computeProjectionStamp({ version: "a", registryContent: "bd" }),
    );
  });

  /**
   * Pinned so the input set cannot grow unnoticed. Every input has to be
   * computable identically by the writer and by each reader, and the readers
   * run from separate copies of one version — the global CLI, the Claude hook
   * shims, the plugin in OpenCode's npm cache. An input any of them resolves
   * differently makes the projection permanently stale to that reader, which is
   * what the running install's path did before it was removed.
   */
  test("hashes exactly the version and the repo-local registry", () => {
    expect(computeProjectionStamp(inputs)).toBe(
      "cdeffa3a4e4ddc0ca51f831e7310796a59fc974e601e0e274630c53613d14836",
    );
  });
});

describe("renderers", () => {
  test("the yaml form round-trips and is marked generated", () => {
    const rendered = renderProjectionYaml(file());
    expect(rendered.startsWith(`# generated by ${FRAMEWORK_NAME}`)).toBe(true);
    expect(parseProjectionYaml(rendered)).toEqual(file());
  });

  test("the env form quotes values so paths containing spaces survive sourcing", () => {
    const spaced = "/Users/a b/My Companions/acme";
    const rendered = renderProjectionEnv(file({ companionPath: spaced }));
    expect(rendered).toContain(`MATE_ARTIFACT_PATH='${spaced}'`);
    expect(rendered).toContain(`${PROJECTION_STAMP_ENV_NAME}='deadbeef'`);
  });

  test("a POSIX shell sources each value as a single word", () => {
    const spaced = "/Users/a b/O'Brien & co/acme";
    const dir = makeTempDir("projection-source-");
    const envFile = path.join(dir, "projection.env");
    fs.writeFileSync(envFile, renderProjectionEnv(file({ companionPath: spaced })), "utf8");

    const result = Bun.spawnSync([
      "sh",
      "-c",
      `. "${envFile}"; set -- $MATE_ARTIFACT_PATH; printf '%s' "$#"; printf '\\n%s' "$MATE_ARTIFACT_PATH"`,
    ]);
    const [wordCount, value] = result.stdout.toString().split("\n");
    expect(Number(wordCount)).toBeGreaterThan(1);
    expect(value).toBe(spaced);
  });

  test("both forms agree: any projected value round-trips identically through either", () => {
    const awkward = [
      "/plain/path",
      "/with space/dir",
      "/with 'single' quote",
      '/with "double" quote',
      "/with $VAR and `cmd`",
      "/with #hash and \\backslash",
      "/with = equals",
      "/with\ttab",
      "0.16.0-canary.1+build.2",
      "",
    ];

    for (const value of awkward) {
      const candidate: ProjectionFile = {
        stamp: `stamp ${value}`,
        projection: Object.fromEntries(
          PROJECTION_FIELDS.map((field) => [field, value]),
        ) as MateProjection,
      };
      expect(parseProjectionYaml(renderProjectionYaml(candidate))).toEqual(candidate);
      expect(parseProjectionEnv(renderProjectionEnv(candidate))).toEqual(candidate);
    }
  });

  test("rejects a truncated or predicate-shaped document instead of throwing", () => {
    expect(parseProjectionYaml(renderProjectionYaml(file()).slice(0, 40))).toBeNull();
    expect(parseProjectionYaml("stamp: only\n")).toBeNull();
    expect(parseProjectionYaml("[unbalanced\n")).toBeNull();
    expect(parseProjectionEnv("MATE_ARTIFACT_PATH=unquoted\n")).toBeNull();
    expect(parseProjectionEnv(renderProjectionEnv(file()).slice(0, 60))).toBeNull();
  });
});

describe("writeProjectionPair", () => {
  test("puts both files directly under the repo-local directory, leaving config alone", () => {
    const repoRoot = makeTempDir("projection-write-");
    writeRepoLocalRegistry(repoRoot);
    const configBefore = fs.readFileSync(repoLocalRegistryPath(repoRoot), "utf8");

    writeProjectionPair(repoRoot, file());

    expect(fs.existsSync(projectionYamlPath(repoRoot))).toBe(true);
    expect(fs.existsSync(projectionEnvPath(repoRoot))).toBe(true);
    expect(path.dirname(projectionYamlPath(repoRoot))).toBe(
      path.join(repoRoot, `.${FRAMEWORK_NAME}`),
    );
    expect(fs.readFileSync(repoLocalRegistryPath(repoRoot), "utf8")).toBe(configBefore);
  });

  test("both files describe the same projection and carry the same stamp", () => {
    const repoRoot = makeTempDir("projection-pair-");
    writeProjectionPair(repoRoot, file());

    const yaml = parseProjectionYaml(fs.readFileSync(projectionYamlPath(repoRoot), "utf8"));
    const env = parseProjectionEnv(fs.readFileSync(projectionEnvPath(repoRoot), "utf8"));
    expect(yaml).toEqual(env);
    expect(yaml?.stamp).toBe(env?.stamp);
  });

  test("applies no narrower file mode than a plainly written sibling", () => {
    const repoRoot = makeTempDir("projection-mode-");
    writeProjectionPair(repoRoot, file());
    const control = path.join(repoRoot, "control");
    fs.writeFileSync(control, "", "utf8");
    const expected = fs.statSync(control).mode;

    for (const generated of [projectionYamlPath(repoRoot), projectionEnvPath(repoRoot)]) {
      expect(fs.statSync(generated).mode).toBe(expected);
    }
  });

  test("leaves no temporary sibling behind and replaces both files together", () => {
    const repoRoot = makeTempDir("projection-refresh-");
    writeProjectionPair(repoRoot, file());
    writeProjectionPair(repoRoot, {
      stamp: "second",
      projection: projection({ repositoryId: "b" }),
    });

    const entries = fs.readdirSync(path.join(repoRoot, `.${FRAMEWORK_NAME}`));
    expect(entries.filter((entry) => entry.endsWith(".tmp"))).toEqual([]);
    expect(readProjectionFile(repoRoot)?.stamp).toBe("second");
    expect(parseProjectionEnv(fs.readFileSync(projectionEnvPath(repoRoot), "utf8"))?.stamp).toBe(
      "second",
    );
  });

  test("a failed render leaves the previous pair intact", () => {
    const repoRoot = makeTempDir("projection-atomic-");
    writeProjectionPair(repoRoot, file());
    const before = fs.readFileSync(projectionYamlPath(repoRoot), "utf8");

    const poisoned = {
      stamp: "next",
      projection: new Proxy(projection(), {
        get(target, key) {
          if (key === "graphifyOut") throw new Error("render failed");
          return target[key as keyof MateProjection];
        },
      }),
    } as ProjectionFile;

    expect(() => writeProjectionPair(repoRoot, poisoned)).toThrow("render failed");
    expect(fs.readFileSync(projectionYamlPath(repoRoot), "utf8")).toBe(before);
    expect(
      fs.readdirSync(path.join(repoRoot, `.${FRAMEWORK_NAME}`)).filter((e) => e.endsWith(".tmp")),
    ).toEqual([]);
  });
});

describe("findRepoLocalRegistryFileSync", () => {
  test("finds the nearest ancestor holding a repo-local registry", () => {
    const repoRoot = makeTempDir("sync-walk-");
    writeRepoLocalRegistry(repoRoot);
    const nested = path.join(repoRoot, "packages", "acme", "src");
    fs.mkdirSync(nested, { recursive: true });

    expect(findRepoLocalRegistryFileSync(nested)).toEqual({
      repoRoot,
      registryPath: repoLocalRegistryPath(repoRoot),
    });
  });

  test("reports nothing rather than throwing when no ancestor has one", () => {
    expect(findRepoLocalRegistryFileSync(makeTempDir("sync-walk-none-"))).toBeNull();
  });
});

describe("resolveProjection", () => {
  test("returns the projected paths recorded at the repository root", () => {
    const repoRoot = makeTempDir("resolve-nested-");
    writeRepoLocalRegistry(repoRoot);
    writeProjectionPair(repoRoot, file());
    const nested = path.join(repoRoot, "apps", "acme", "src");
    fs.mkdirSync(nested, { recursive: true });

    expect(resolveProjection(nested)).toEqual({ repoRoot, stamp: "deadbeef", ...projection() });
  });

  test("reports the recorded stamp alongside the projected paths", () => {
    const repoRoot = makeTempDir("resolve-stamp-");
    writeRepoLocalRegistry(repoRoot);
    writeProjectionPair(repoRoot, { stamp: "feedface", projection: projection() });

    expect(resolveProjection(repoRoot)?.stamp).toBe("feedface");
  });

  test("an intermediate projection without a registry does not shadow the registry root", () => {
    const repoRoot = makeTempDir("resolve-shadow-");
    writeRepoLocalRegistry(repoRoot);
    writeProjectionPair(repoRoot, file());

    const intermediate = path.join(repoRoot, "packages", "acme");
    fs.mkdirSync(intermediate, { recursive: true });
    writeProjectionPair(intermediate, file({ companionPath: "/companions/shadow" }));

    expect(resolveProjection(path.join(intermediate, "src"))?.companionPath).toBe(
      "/companions/acme",
    );
  });

  test("reports no projection when no ancestor holds a repo-local registry", () => {
    const orphan = makeTempDir("resolve-no-registry-");
    writeProjectionPair(orphan, file());

    expect(resolveProjection(orphan)).toBeNull();
  });

  test("reports no projection when the registry root carries none", () => {
    const repoRoot = makeTempDir("resolve-no-projection-");
    writeRepoLocalRegistry(repoRoot);

    expect(resolveProjection(repoRoot)).toBeNull();
  });

  test("reports no projection when the projection is unparseable", () => {
    const repoRoot = makeTempDir("resolve-truncated-");
    writeRepoLocalRegistry(repoRoot);
    writeProjectionPair(repoRoot, file());
    const yamlPath = projectionYamlPath(repoRoot);
    fs.writeFileSync(yamlPath, fs.readFileSync(yamlPath, "utf8").slice(0, 45), "utf8");

    expect(resolveProjection(repoRoot)).toBeNull();
  });

  test("does not require the projected companion to exist", () => {
    const repoRoot = makeTempDir("resolve-missing-companion-");
    writeRepoLocalRegistry(repoRoot);
    writeProjectionPair(repoRoot, file({ companionPath: "/companions/gone" }));

    expect(resolveProjection(repoRoot)?.companionPath).toBe("/companions/gone");
  });
});
