import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { parse, stringify } from "yaml";

import { MATE_ENV } from "./env-names";
import { FRAMEWORK_NAME } from "./framework";
import { findRepoLocalRegistryFileSync, repoLocalDirPath } from "./repo-local";

/** Generated projection files, directly under the repo-local `.mate/`. */
export const PROJECTION_YAML_FILE = "projection.yaml";
export const PROJECTION_ENV_FILE = "projection.env";

/**
 * Paths a session needs, projected to disk at the Projection Root. Paths only:
 * a predicate would go stale between refreshes, so predicates are read live
 * from the companion instead. No predicate field is expressible here.
 */
export interface MateProjection {
  version: string;
  companionPath: string;
  repositoryPath: string;
  repositoryId: string;
  wrapperBinPath: string;
  reactDoctorBinPath: string;
  graphifyOut: string;
}

/**
 * Env variable each projected field materializes as. `GRAPHIFY_OUT` is
 * graphify's own variable rather than part of the `MATE_*` contract, so it is
 * spelled here instead of in `MATE_ENV`.
 */
export const PROJECTION_ENV_NAMES: Record<keyof MateProjection, string> = {
  version: MATE_ENV.version,
  companionPath: MATE_ENV.companionPath,
  repositoryPath: MATE_ENV.repositoryPath,
  repositoryId: MATE_ENV.repositoryId,
  wrapperBinPath: MATE_ENV.wrapperBinPath,
  reactDoctorBinPath: MATE_ENV.reactDoctorBinPath,
  graphifyOut: "GRAPHIFY_OUT",
};

/** Stable field order; both renderers iterate it so the forms cannot diverge. */
export const PROJECTION_FIELDS = Object.keys(PROJECTION_ENV_NAMES) as Array<keyof MateProjection>;

export const PROJECTION_STAMP_ENV_NAME = "MATE_PROJECTION_STAMP";

/**
 * Stamp inputs. The companion's `framework.yaml` is deliberately absent: no
 * predicate is projected, so nothing derived from it can go stale.
 */
export interface ProjectionStampInputs {
  version: string;
  installPath: string;
  registryContent: string;
}

/** Both generated files carry the same stamp; a reader regenerates on mismatch. */
export interface ProjectionFile {
  stamp: string;
  projection: MateProjection;
}

export function computeProjectionStamp(inputs: ProjectionStampInputs): string {
  return crypto
    .createHash("sha256")
    .update(inputs.version)
    .update("\0")
    .update(inputs.installPath)
    .update("\0")
    .update(inputs.registryContent)
    .digest("hex");
}

export function projectionYamlPath(repoRoot: string): string {
  return path.join(repoLocalDirPath(repoRoot), PROJECTION_YAML_FILE);
}

export function projectionEnvPath(repoRoot: string): string {
  return path.join(repoLocalDirPath(repoRoot), PROJECTION_ENV_FILE);
}

const generatedHeader = () => `# generated by ${FRAMEWORK_NAME} — do not edit`;

export function renderProjectionYaml(file: ProjectionFile): string {
  const document: Record<string, string> = { stamp: file.stamp };
  for (const field of PROJECTION_FIELDS) document[field] = file.projection[field];
  return `${generatedHeader()}\n${stringify(document)}`;
}

export function parseProjectionYaml(raw: string): ProjectionFile | null {
  let parsed: unknown;
  try {
    parsed = parse(raw);
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== "object") return null;
  return readProjectionRecord(parsed as Record<string, unknown>, (field) => field);
}

/**
 * Single-quoted for `sh`: inside single quotes nothing expands or word-splits,
 * so a path containing spaces survives sourcing intact.
 */
function quoteShellValue(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function unquoteShellValue(value: string): string | null {
  if (value.length < 2 || !value.startsWith("'") || !value.endsWith("'")) return null;
  return value.slice(1, -1).replaceAll(`'\\''`, "'");
}

export function renderProjectionEnv(file: ProjectionFile): string {
  const lines = [generatedHeader(), `${PROJECTION_STAMP_ENV_NAME}=${quoteShellValue(file.stamp)}`];
  for (const field of PROJECTION_FIELDS) {
    lines.push(`${PROJECTION_ENV_NAMES[field]}=${quoteShellValue(file.projection[field])}`);
  }
  return `${lines.join("\n")}\n`;
}

export function parseProjectionEnv(raw: string): ProjectionFile | null {
  const values: Record<string, unknown> = {};
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (trimmed === "" || trimmed.startsWith("#")) continue;
    const separator = trimmed.indexOf("=");
    if (separator <= 0) return null;
    const unquoted = unquoteShellValue(trimmed.slice(separator + 1));
    if (unquoted === null) return null;
    values[trimmed.slice(0, separator)] = unquoted;
  }

  const stamp = values[PROJECTION_STAMP_ENV_NAME];
  if (typeof stamp !== "string") return null;
  return readProjectionRecord({ ...values, stamp }, (field) => PROJECTION_ENV_NAMES[field]);
}

function readProjectionRecord(
  record: Record<string, unknown>,
  keyOf: (field: keyof MateProjection) => string,
): ProjectionFile | null {
  const stamp = record.stamp;
  if (typeof stamp !== "string") return null;

  const projection = {} as MateProjection;
  for (const field of PROJECTION_FIELDS) {
    const value = record[keyOf(field)];
    if (typeof value !== "string") return null;
    projection[field] = value;
  }
  return { stamp, projection };
}

/**
 * Writes both forms as one unit: rendered in memory, written to temporary
 * siblings, then renamed into place, so a reader never observes a fresh
 * `.yaml` beside a stale `.env`. Default file mode — the projection holds only
 * paths already visible in the working tree's config, so it is not restricted.
 */
export function writeProjectionPair(repoRoot: string, file: ProjectionFile): void {
  const yamlPath = projectionYamlPath(repoRoot);
  const envPath = projectionEnvPath(repoRoot);
  const suffix = `.${crypto.randomUUID()}.tmp`;
  const yamlTempPath = `${yamlPath}${suffix}`;
  const envTempPath = `${envPath}${suffix}`;

  fs.mkdirSync(path.dirname(yamlPath), { recursive: true });
  try {
    fs.writeFileSync(yamlTempPath, renderProjectionYaml(file), "utf8");
    fs.writeFileSync(envTempPath, renderProjectionEnv(file), "utf8");
    fs.renameSync(yamlTempPath, yamlPath);
    fs.renameSync(envTempPath, envPath);
  } catch (error) {
    for (const tempPath of [yamlTempPath, envTempPath]) {
      try {
        fs.rmSync(tempPath, { force: true });
      } catch {
        // best-effort cleanup
      }
    }
    throw error;
  }
}

export function readProjectionFile(repoRoot: string): ProjectionFile | null {
  try {
    return parseProjectionYaml(fs.readFileSync(projectionYamlPath(repoRoot), "utf8"));
  } catch {
    return null;
  }
}

export interface ResolvedProjection extends MateProjection {
  repoRoot: string;
  /** Recorded, never judged here: the verdict needs inputs this module lacks. */
  stamp: string;
}

/**
 * Synchronous, paths only, so a hook or shell that cannot await can use it.
 * Anchored to the directory holding the repo-local `registry.yaml` rather than
 * walking independently for `projection.yaml`, so it cannot resolve a
 * projection belonging to a different ancestor than the registry does. The
 * projected `companionPath` is not stat-ed: a reader that needs the companion
 * to exist fails in its own terms.
 */
export function resolveProjection(cwd: string): ResolvedProjection | null {
  const found = findRepoLocalRegistryFileSync(cwd);
  if (!found) return null;

  const file = readProjectionFile(found.repoRoot);
  if (!file) return null;
  return { repoRoot: found.repoRoot, stamp: file.stamp, ...file.projection };
}
