import { execFile as execFileCb } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

import { getOpenSpecSchemaSelection } from "../../../lib/orchestrator/setup-compatibilities";
import { fetchPublicPackageVersion } from "../../../lib/public-npm";
import { isNewer } from "../../../lib/update-checker";
import { confirm } from "../../../cli/confirm";
import type { CapabilityPlugin, SetupContext } from "../plugin";
import type { InstallRequirement } from "../install-contract";
import {
  isCommandOnPath,
  mergeDir,
  pruneEmptyAncestors,
  resolveCommandOnPath,
  runCommand,
  runCommandSilently,
} from "../utils";

const execFileAsync = promisify(execFileCb);

export const OPENSPEC_SKILLS = [
  "openspec-explore",
  "openspec-propose",
  "openspec-apply-change",
  "openspec-archive-change",
] as const;

// Mate-authored skills (not generated by the openspec CLI) that ship alongside the
// openspec workflow skills and are installed per active provider.
export const MATE_OPENSPEC_SKILLS = ["mate-openspec-artifact-finish"] as const;

const MATE_SKILLS_SOURCE = path.join(
  import.meta.dirname,
  "../../../templates/capabilities/openspec-cap/mate-skills",
);

const MATE_V1_SCHEMA_SOURCE = path.join(
  import.meta.dirname,
  "../../../templates/capabilities/openspec-cap/mate-v1",
);

const CLAUDE_HOOK_SOURCE = path.join(
  import.meta.dirname,
  "../../../templates/capabilities/openspec-cap/claude/hooks/mate-openspec-artifact-finish.sh",
);

const OPENSPEC_TOOL_DIRS = {
  claude: ".claude",
  codex: ".codex",
  opencode: ".opencode",
} as const;

const OPENSPEC_INSTALL_COMMAND = "npm install -g @fission-ai/openspec@latest";

type OpenSpecTool = keyof typeof OPENSPEC_TOOL_DIRS;
type OpenSpecRunCommand = typeof runCommandSilently;

export interface OpenSpecPluginDeps {
  runCommand?: OpenSpecRunCommand;
  installCommand?: typeof runCommand;
  isCommandOnPath?: typeof isCommandOnPath;
  confirm?: typeof confirm;
  pathValue?: () => string;
  getInstalledVersion?: (pathValue: string) => Promise<string | undefined>;
  fetchLatestVersion?: () => Promise<string | undefined>;
}

const OPEN_SPEC_SUPPORTED_TOOLS = Object.keys(OPENSPEC_TOOL_DIRS) as OpenSpecTool[];

async function defaultGetInstalledVersion(pathValue: string): Promise<string | undefined> {
  const bin = resolveCommandOnPath("openspec", pathValue);
  if (!bin) return undefined;

  try {
    const { stdout } = await execFileAsync(bin, ["--version"], { timeout: 10_000 });
    return stdout.match(/\d+\.\d+\.\d+/)?.[0];
  } catch {
    return undefined;
  }
}

async function defaultFetchLatestVersion(): Promise<string | undefined> {
  try {
    return await fetchPublicPackageVersion("@fission-ai/openspec");
  } catch {
    return undefined;
  }
}

export function deriveOpenSpecTools(activeProviders: string[]): OpenSpecTool[] {
  return OPEN_SPEC_SUPPORTED_TOOLS.filter((tool) => activeProviders.includes(tool));
}

function getSkillsDir(companionPath: string, tool: OpenSpecTool): string {
  return path.join(companionPath, OPENSPEC_TOOL_DIRS[tool], "skills");
}

function getOpenSpecConfigPath(companionPath: string): string {
  return path.join(companionPath, "openspec", "config.yaml");
}

function getMateV1SchemaDir(companionPath: string): string {
  return path.join(companionPath, "openspec", "schemas", "mate-v1");
}

export async function teardownOpenspecSkills(
  skillsDir: string,
  companionPath: string,
): Promise<void> {
  for (const skill of [...OPENSPEC_SKILLS, ...MATE_OPENSPEC_SKILLS]) {
    try {
      await fs.rm(path.join(skillsDir, skill), { recursive: true, force: true });
    } catch {
      /* not present */
    }
  }
  await pruneEmptyAncestors(skillsDir, companionPath);
}

async function teardownMateOpenspecSkills(skillsDir: string, companionPath: string): Promise<void> {
  for (const skill of MATE_OPENSPEC_SKILLS) {
    try {
      await fs.rm(path.join(skillsDir, skill), { recursive: true, force: true });
    } catch {
      /* not present */
    }
  }
  await pruneEmptyAncestors(skillsDir, companionPath);
}

async function teardownToolRuntime(companionPath: string, tool: OpenSpecTool): Promise<void> {
  await teardownOpenspecSkills(getSkillsDir(companionPath, tool), companionPath);
}

async function applyMateOpenspecSkills(
  companionPath: string,
  tools: OpenSpecTool[],
): Promise<void> {
  for (const tool of tools) {
    const skillsDir = getSkillsDir(companionPath, tool);
    for (const skill of MATE_OPENSPEC_SKILLS) {
      await mergeDir(path.join(MATE_SKILLS_SOURCE, skill), path.join(skillsDir, skill));
    }
  }
}

async function reconcileOpenSpecTools(
  ctx: SetupContext,
  runCommand: OpenSpecRunCommand,
): Promise<void> {
  const tools = deriveOpenSpecTools(ctx.activeProviders);
  if (tools.length === 0) return;

  const codexEnv = tools.includes("codex")
    ? { env: { ...process.env, CODEX_HOME: path.join(ctx.companionPath, ".codex") } }
    : {};
  await runCommand("openspec", ["init", "--tools", tools.join(","), "--force", ctx.companionPath], {
    cwd: ctx.companionPath,
    ...codexEnv,
  });
  await runCommand("openspec", ["update", "--force", ctx.companionPath], {
    cwd: ctx.companionPath,
    ...codexEnv,
  });

  // The openspec CLI generates its own workflow skills above; layer the
  // mate-authored skills on top for the same active providers.
  if (ctx.config.git === "auto") {
    await applyMateOpenspecSkills(ctx.companionPath, tools);
  } else {
    for (const tool of tools) {
      await teardownMateOpenspecSkills(getSkillsDir(ctx.companionPath, tool), ctx.companionPath);
    }
  }
}

async function warnIfOpenSpecOutdated(
  ctx: SetupContext,
  deps: Required<
    Pick<
      OpenSpecPluginDeps,
      "installCommand" | "confirm" | "pathValue" | "getInstalledVersion" | "fetchLatestVersion"
    >
  >,
): Promise<void> {
  const installed = await deps.getInstalledVersion(deps.pathValue());
  if (!installed) return;

  const latest = await deps.fetchLatestVersion();
  if (!latest || !isNewer(latest, installed)) return;

  if (ctx.mode !== "setup") {
    process.stderr.write(
      `openspec: installed version ${installed} is outdated (latest ${latest}). Run \`${OPENSPEC_INSTALL_COMMAND}\` to upgrade.\n`,
    );
    return;
  }

  process.stdout.write(
    `openspec: installed version ${installed} is outdated (latest ${latest}).\n  ${OPENSPEC_INSTALL_COMMAND}\n`,
  );
  const ok = await deps.confirm("Upgrade openspec now?");
  if (!ok) {
    process.stderr.write("openspec: upgrade skipped - continuing with the installed version\n");
    return;
  }

  try {
    await deps.installCommand("npm", ["install", "-g", "@fission-ai/openspec@latest"], {
      cwd: ctx.companionPath,
    });
  } catch {
    process.stderr.write("openspec: upgrade failed - continuing with the installed version\n");
  }
}

async function ensureOpenSpecInstalled(
  ctx: SetupContext,
  deps: Required<
    Pick<
      OpenSpecPluginDeps,
      | "installCommand"
      | "isCommandOnPath"
      | "confirm"
      | "pathValue"
      | "getInstalledVersion"
      | "fetchLatestVersion"
    >
  >,
): Promise<boolean> {
  if (deps.isCommandOnPath("openspec", deps.pathValue())) {
    await warnIfOpenSpecOutdated(ctx, deps);
    return true;
  }

  if (ctx.mode !== "setup") {
    process.stderr.write(
      `openspec binary not found. Install it manually with \`${OPENSPEC_INSTALL_COMMAND}\`\n`,
    );
    return false;
  }

  if (!deps.isCommandOnPath("npm", deps.pathValue())) {
    process.stderr.write(
      `openspec binary not found and npm is not available on PATH. Install it manually with \`${OPENSPEC_INSTALL_COMMAND}\`\n`,
    );
    return false;
  }

  process.stdout.write(`openspec binary not found. To install:\n  ${OPENSPEC_INSTALL_COMMAND}\n`);
  const ok = await deps.confirm("Run this install command now?");
  if (!ok) {
    process.stderr.write(
      `openspec: install skipped - install manually with \`${OPENSPEC_INSTALL_COMMAND}\`\n`,
    );
    return false;
  }

  try {
    await deps.installCommand("npm", ["install", "-g", "@fission-ai/openspec@latest"], {
      cwd: ctx.companionPath,
    });
  } catch {
    process.stderr.write(
      `openspec: install failed - install manually with \`${OPENSPEC_INSTALL_COMMAND}\`\n`,
    );
    return false;
  }

  if (!deps.isCommandOnPath("openspec", deps.pathValue())) {
    process.stderr.write(
      "openspec install completed but the binary is still not available on PATH\n",
    );
    return false;
  }

  return true;
}

async function teardownOpenSpecSchema(companionPath: string): Promise<void> {
  const schemaDir = getMateV1SchemaDir(companionPath);
  await fs.rm(schemaDir, { recursive: true, force: true });
  await pruneEmptyAncestors(schemaDir, companionPath);

  const configPath = getOpenSpecConfigPath(companionPath);
  try {
    const content = await fs.readFile(configPath, "utf8");
    if (content.trim() === "schema: mate-v1") {
      await fs.rm(configPath, { force: true });
      await pruneEmptyAncestors(path.dirname(configPath), companionPath);
    }
  } catch {
    /* no managed config present */
  }
}

async function reconcileOpenSpecSchema(ctx: SetupContext): Promise<void> {
  if (getOpenSpecSchemaSelection(ctx.config.capabilities ?? []) !== "mate-v1") {
    await teardownOpenSpecSchema(ctx.companionPath);
    return;
  }

  await mergeDir(MATE_V1_SCHEMA_SOURCE, getMateV1SchemaDir(ctx.companionPath));
  const configPath = getOpenSpecConfigPath(ctx.companionPath);
  await fs.mkdir(path.dirname(configPath), { recursive: true });

  // config.yaml is user-editable once created; never overwrite it on re-sync.
  const configExists = await fs
    .access(configPath)
    .then(() => true)
    .catch(() => false);
  if (configExists) return;

  await fs.writeFile(configPath, "schema: mate-v1\n", "utf8");
}

export function createOpenspecPlugin(deps: OpenSpecPluginDeps = {}): CapabilityPlugin {
  const depsWithDefaults = {
    runCommand: deps.runCommand ?? runCommandSilently,
    installCommand: deps.installCommand ?? runCommand,
    isCommandOnPath: deps.isCommandOnPath ?? isCommandOnPath,
    confirm: deps.confirm ?? confirm,
    pathValue: deps.pathValue ?? (() => process.env.PATH ?? ""),
    getInstalledVersion: deps.getInstalledVersion ?? defaultGetInstalledVersion,
    fetchLatestVersion: deps.fetchLatestVersion ?? defaultFetchLatestVersion,
  };

  return {
    id: "openspec",
    kind: "capability",
    label: "OpenSpec",
    description: "Route OpenSpec commands to the companion root and enable planning workflows.",
    defaultSelected: true,
    isEnabled: (config) => (config.capabilities ?? []).some((c) => c.name === "openspec"),
    getInstallRequirements: (): InstallRequirement[] => [
      {
        id: "capability:openspec",
        label: "OpenSpec CLI",
        group: "companion",
        source: "OpenSpec capability",
        command: OPENSPEC_INSTALL_COMMAND,
        fingerprint: `openspec:${OPENSPEC_INSTALL_COMMAND}`,
        detect: () => depsWithDefaults.isCommandOnPath("openspec", depsWithDefaults.pathValue()),
        install: () =>
          depsWithDefaults.installCommand("npm", ["install", "-g", "@fission-ai/openspec@latest"]),
        verify: () => depsWithDefaults.isCommandOnPath("openspec", depsWithDefaults.pathValue()),
      },
    ],
    async apply(ctx) {
      const tools = deriveOpenSpecTools(ctx.activeProviders);
      if (tools.length > 0 && (await ensureOpenSpecInstalled(ctx, depsWithDefaults))) {
        await reconcileOpenSpecTools(ctx, depsWithDefaults.runCommand);
      }
      await reconcileOpenSpecSchema(ctx);
    },
    async teardown(ctx) {
      for (const tool of OPEN_SPEC_SUPPORTED_TOOLS) {
        await teardownToolRuntime(ctx.companionPath, tool);
      }
      await teardownOpenSpecSchema(ctx.companionPath);
    },
    forProvider: {
      claude: {
        async apply(ctx: SetupContext) {
          if (ctx.config.git !== "auto") {
            return;
          }
          const hookDest = path.join(
            ctx.companionPath,
            ".claude",
            "hooks",
            "mate-openspec-artifact-finish.sh",
          );
          await fs.mkdir(path.dirname(hookDest), { recursive: true });
          await fs.copyFile(CLAUDE_HOOK_SOURCE, hookDest);
          await fs.chmod(hookDest, 0o755);
        },
        async teardown(ctx: SetupContext) {
          try {
            await fs.unlink(
              path.join(ctx.companionPath, ".claude", "hooks", "mate-openspec-artifact-finish.sh"),
            );
          } catch {
            /* not present */
          }
          await pruneEmptyAncestors(
            path.join(ctx.companionPath, ".claude", "hooks"),
            ctx.companionPath,
          );
          await teardownToolRuntime(ctx.companionPath, "claude");
        },
      },
      codex: {
        async apply(ctx: SetupContext) {
          if (ctx.config.git !== "auto") return;
          const hookDest = path.join(
            ctx.companionPath,
            ".codex",
            "hooks",
            "mate-openspec-artifact-finish.cjs",
          );
          await fs.mkdir(path.dirname(hookDest), { recursive: true });
          await fs.copyFile(
            path.join(
              import.meta.dirname,
              "../../../templates/capabilities/openspec-cap/codex/hooks/mate-openspec-artifact-finish.cjs",
            ),
            hookDest,
          );
          const { reconcileCompanionCodexHookGroup } = await import("../providers/codex");
          await reconcileCompanionCodexHookGroup(
            ctx.companionPath,
            "PostToolUse",
            "/.codex/hooks/mate-openspec-artifact-finish",
            {
              matcher: "Bash|exec_command",
              hooks: [
                {
                  type: "command",
                  command: `node "${hookDest}"`,
                  timeout: 30,
                },
              ],
            },
          );
        },
        async teardown(ctx: SetupContext) {
          await fs.rm(
            path.join(ctx.companionPath, ".codex", "hooks", "mate-openspec-artifact-finish.cjs"),
            { force: true },
          );
          if (ctx.activeProviders.includes("codex")) {
            const { reconcileCompanionCodexHookGroup } = await import("../providers/codex");
            await reconcileCompanionCodexHookGroup(
              ctx.companionPath,
              "PostToolUse",
              "/.codex/hooks/mate-openspec-artifact-finish",
            );
          }
          await teardownToolRuntime(ctx.companionPath, "codex");
        },
      },
      opencode: {
        async apply() {},
        async teardown(ctx: SetupContext) {
          await teardownToolRuntime(ctx.companionPath, "opencode");
        },
      },
    },
  };
}

export const openspecPlugin = createOpenspecPlugin();
