import { execFile as execFileCb } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

import { getOpenSpecSchemaSelection } from "../../../lib/orchestrator/setup-compatibilities";
import { getWrapperBinPath } from "../../../lib/package-paths";
import { fetchPublicPackageVersion } from "../../../lib/public-npm";
import { isNewer } from "../../../lib/update-checker";
import { FRAMEWORK_NAME } from "../../../framework";
import { confirm } from "../../../cli/confirm";
import type { CapabilityPlugin, RuntimeContributionsByRuntime, SetupContext } from "../plugin";
import type { InstallRequirement } from "../install-contract";
import {
  isCommandOnPath,
  mergeDir,
  pruneEmptyAncestors,
  resolveCommandOnPath,
  runCommand,
  runCommandSilently,
} from "../utils";
import { applyMateSkills, teardownMateSkills } from "../mate";

export { MATE_ARTIFACT_SKILLS, MATE_SKILLS, deployMateSkillDir } from "../mate";

const execFileAsync = promisify(execFileCb);

export const OPENSPEC_SKILLS = [
  "openspec-explore",
  "openspec-propose",
  "openspec-apply-change",
  "openspec-archive-change",
] as const;

// Mate-authored skills (not generated by the openspec CLI) are sourced from the
// shared Mate skill tree and installed per active provider while OpenSpec is enabled.
const LEGACY_CLAUDE_STATE_PATTERN = /^mate-artifact-finish\..+\.json$/;

/** Every Mate-owned schema is installed for availability; only one is ever activated as the companion default. */
const MATE_SCHEMA_NAMES = ["mate-v1", "mate-minimal"] as const;

const MATE_SCHEMA_SOURCE_ROOT = path.join(
  import.meta.dirname,
  "../../../templates/capabilities/openspec-cap",
);
const MATE_CONVENTIONS_SOURCE = path.join(MATE_SCHEMA_SOURCE_ROOT, "openspec-conventions.yaml");

const OPENSPEC_TOOL_DIRS = {
  claude: ".claude",
  opencode: ".opencode",
} as const;

const OPENSPEC_INSTALL_COMMAND = "npm install -g @fission-ai/openspec@latest";

type OpenSpecTool = keyof typeof OPENSPEC_TOOL_DIRS;
type OpenSpecRunCommand = typeof runCommandSilently;

export interface OpenSpecPluginDeps {
  runCommand?: OpenSpecRunCommand;
  installCommand?: typeof runCommand;
  isCommandOnPath?: typeof isCommandOnPath;
  confirm?: typeof confirm;
  pathValue?: () => string;
  wrapperBinPath?: () => string;
  getInstalledVersion?: (pathValue: string) => Promise<string | undefined>;
  fetchLatestVersion?: () => Promise<string | undefined>;
}

const OPEN_SPEC_SUPPORTED_TOOLS = Object.keys(OPENSPEC_TOOL_DIRS) as OpenSpecTool[];

async function defaultGetInstalledVersion(pathValue: string): Promise<string | undefined> {
  const bin = resolveCommandOnPath("openspec", pathValue);
  if (!bin) return undefined;

  try {
    const { stdout } = await execFileAsync(bin, ["--version"], { timeout: 10_000 });
    return stdout.match(/\d+\.\d+\.\d+/)?.[0];
  } catch {
    return undefined;
  }
}

async function defaultFetchLatestVersion(): Promise<string | undefined> {
  try {
    return await fetchPublicPackageVersion("@fission-ai/openspec");
  } catch {
    return undefined;
  }
}

export function deriveOpenSpecTools(activeProviders: string[]): OpenSpecTool[] {
  return OPEN_SPEC_SUPPORTED_TOOLS.filter((tool) => activeProviders.includes(tool));
}

function getSkillsDir(companionPath: string, tool: OpenSpecTool): string {
  return path.join(companionPath, OPENSPEC_TOOL_DIRS[tool], "skills");
}

function getOpenSpecConfigPath(companionPath: string): string {
  return path.join(companionPath, "openspec", "config.yaml");
}

function getMateSchemaDir(companionPath: string, schemaName: string): string {
  return path.join(companionPath, "openspec", "schemas", schemaName);
}

function getMateConventionsPath(companionPath: string): string {
  return path.join(companionPath, "openspec", "mate-conventions.yaml");
}

export async function teardownOpenspecSkills(
  skillsDir: string,
  companionPath: string,
): Promise<void> {
  for (const skill of OPENSPEC_SKILLS) {
    try {
      await fs.rm(path.join(skillsDir, skill), { recursive: true, force: true });
    } catch {
      /* not present */
    }
  }
  await teardownMateSkills(skillsDir, companionPath);
  await pruneEmptyAncestors(skillsDir, companionPath);
}

async function teardownToolRuntime(companionPath: string, tool: OpenSpecTool): Promise<void> {
  await teardownOpenspecSkills(getSkillsDir(companionPath, tool), companionPath);
}

async function applyMateOpenspecSkills(
  companionPath: string,
  tools: OpenSpecTool[],
): Promise<void> {
  for (const tool of tools) {
    const skillsDir = getSkillsDir(companionPath, tool);
    await applyMateSkills(skillsDir, tool);
  }
}

async function reconcileOpenSpecTools(
  ctx: SetupContext,
  runCommand: OpenSpecRunCommand,
): Promise<void> {
  const tools = deriveOpenSpecTools(ctx.activeProviders);
  if (tools.length === 0) return;
  /** Best-effort: `config reset` is missing on older openspec releases. */
  try {
    await runCommand("openspec", ["config", "reset", "--all", "-y"], {
      cwd: ctx.companionPath,
    });
  } catch (error) {
    process.stderr.write(
      `openspec config reset skipped: ${error instanceof Error ? error.message : String(error)}\n`,
    );
  }

  await runCommand("openspec", ["init", "--tools", tools.join(","), "--force", ctx.companionPath], {
    cwd: ctx.companionPath,
  });
  await runCommand("openspec", ["update", "--force", ctx.companionPath], {
    cwd: ctx.companionPath,
  });

  // The openspec CLI generates its own workflow skills above; layer the
  // mate-authored skills on top for the same active providers.
  await applyMateOpenspecSkills(ctx.companionPath, tools);
}

async function updateOpenSpecIfOutdated(
  ctx: SetupContext,
  deps: Required<
    Pick<
      OpenSpecPluginDeps,
      "installCommand" | "pathValue" | "getInstalledVersion" | "fetchLatestVersion"
    >
  >,
): Promise<void> {
  const installed = await deps.getInstalledVersion(deps.pathValue());
  if (!installed) return;

  const latest = await deps.fetchLatestVersion();
  if (!latest || !isNewer(latest, installed)) return;

  process.stdout.write(
    `openspec: installed version ${installed} is outdated (latest ${latest}). Updating now:\n  ${OPENSPEC_INSTALL_COMMAND}\n`,
  );

  try {
    await deps.installCommand("npm", ["install", "-g", "@fission-ai/openspec@latest"], {
      cwd: ctx.companionPath,
    });
  } catch {
    process.stderr.write("openspec: upgrade failed - continuing with the installed version\n");
  }
}

async function ensureOpenSpecInstalled(
  ctx: SetupContext,
  deps: Required<
    Pick<
      OpenSpecPluginDeps,
      | "installCommand"
      | "isCommandOnPath"
      | "confirm"
      | "pathValue"
      | "getInstalledVersion"
      | "fetchLatestVersion"
    >
  >,
): Promise<boolean> {
  if (deps.isCommandOnPath("openspec", deps.pathValue())) {
    await updateOpenSpecIfOutdated(ctx, deps);
    return true;
  }

  if (ctx.mode !== "setup") {
    process.stderr.write(
      `openspec binary not found. Install it manually with \`${OPENSPEC_INSTALL_COMMAND}\`\n`,
    );
    return false;
  }

  if (!deps.isCommandOnPath("npm", deps.pathValue())) {
    process.stderr.write(
      `openspec binary not found and npm is not available on PATH. Install it manually with \`${OPENSPEC_INSTALL_COMMAND}\`\n`,
    );
    return false;
  }

  process.stdout.write(`openspec binary not found. To install:\n  ${OPENSPEC_INSTALL_COMMAND}\n`);
  const ok = await deps.confirm("Run this install command now?");
  if (!ok) {
    process.stderr.write(
      `openspec: install skipped - install manually with \`${OPENSPEC_INSTALL_COMMAND}\`\n`,
    );
    return false;
  }

  try {
    await deps.installCommand("npm", ["install", "-g", "@fission-ai/openspec@latest"], {
      cwd: ctx.companionPath,
    });
  } catch {
    process.stderr.write(
      `openspec: install failed - install manually with \`${OPENSPEC_INSTALL_COMMAND}\`\n`,
    );
    return false;
  }

  if (!deps.isCommandOnPath("openspec", deps.pathValue())) {
    process.stderr.write(
      "openspec install completed but the binary is still not available on PATH\n",
    );
    return false;
  }

  return true;
}

/** Only the config Mate itself wrote is removed; a user-edited config.yaml is left alone. */
async function removeManagedOpenSpecConfig(companionPath: string): Promise<void> {
  const configPath = getOpenSpecConfigPath(companionPath);
  try {
    const content = await fs.readFile(configPath, "utf8");
    if (content.trim() === "schema: mate-v1") {
      await fs.rm(configPath, { force: true });
      await pruneEmptyAncestors(path.dirname(configPath), companionPath);
    }
  } catch {
    /* no managed config present */
  }
}

async function teardownOpenSpecSchema(companionPath: string): Promise<void> {
  for (const schemaName of MATE_SCHEMA_NAMES) {
    const schemaDir = getMateSchemaDir(companionPath, schemaName);
    await fs.rm(schemaDir, { recursive: true, force: true });
    await pruneEmptyAncestors(schemaDir, companionPath);
  }

  await fs.rm(getMateConventionsPath(companionPath), { force: true });
  await removeManagedOpenSpecConfig(companionPath);
}

async function reconcileOpenSpecSchema(ctx: SetupContext): Promise<void> {
  await Promise.all(
    MATE_SCHEMA_NAMES.map((schemaName) =>
      mergeDir(
        path.join(MATE_SCHEMA_SOURCE_ROOT, schemaName),
        getMateSchemaDir(ctx.companionPath, schemaName),
      ),
    ),
  );
  await fs.rm(
    path.join(getMateSchemaDir(ctx.companionPath, "mate-v1"), "templates", "explore-brief.md"),
    { force: true },
  );
  await fs.copyFile(MATE_CONVENTIONS_SOURCE, getMateConventionsPath(ctx.companionPath));

  // Availability is unconditional so any change may select a Mate schema;
  // activation stays opt-in through the companion-level setup selection.
  if (getOpenSpecSchemaSelection(ctx.config.capabilities ?? []) !== "mate-v1") {
    await removeManagedOpenSpecConfig(ctx.companionPath);
    return;
  }

  const configPath = getOpenSpecConfigPath(ctx.companionPath);
  await fs.mkdir(path.dirname(configPath), { recursive: true });

  // config.yaml is user-editable once created; never overwrite it on re-sync.
  const configExists = await fs
    .access(configPath)
    .then(() => true)
    .catch(() => false);
  if (configExists) return;

  await fs.writeFile(configPath, "schema: mate-v1\n", "utf8");
}

export function createOpenspecPlugin(deps: OpenSpecPluginDeps = {}): CapabilityPlugin {
  const depsWithDefaults = {
    runCommand: deps.runCommand ?? runCommandSilently,
    installCommand: deps.installCommand ?? runCommand,
    isCommandOnPath: deps.isCommandOnPath ?? isCommandOnPath,
    confirm: deps.confirm ?? confirm,
    pathValue: deps.pathValue ?? (() => process.env.PATH ?? ""),
    wrapperBinPath: deps.wrapperBinPath ?? getWrapperBinPath,
    getInstalledVersion: deps.getInstalledVersion ?? defaultGetInstalledVersion,
    fetchLatestVersion: deps.fetchLatestVersion ?? defaultFetchLatestVersion,
  };

  return {
    id: "openspec",
    kind: "capability",
    label: "OpenSpec",
    description: "Route OpenSpec commands to the companion root and enable planning workflows.",
    defaultSelected: true,
    isEnabled: (config) => (config.capabilities ?? []).some((c) => c.name === "openspec"),
    // Permission pre-seeds are declared and reconciled by the Claude Runtime
    // Surface. Skill trees stay imperative on purpose: the workflow skills are
    // written by the external `openspec` CLI (foreign trees), and the
    // mate-authored skills are git-mode-conditional with per-tool sources.
    getRuntimeContributions(): RuntimeContributionsByRuntime {
      return {
        claude: {
          permissionEntries: [
            "Skill(openspec-explore)",
            "Skill(openspec-propose)",
            "Skill(openspec-apply-change)",
            "Skill(openspec-archive-change)",
            "Skill(mate-artifact-finish)",
            "Skill(mate-openspec-backfill)",
            "Skill(mate-interview-me)",
            "Skill(mate-grill-me)",
            "Skill(mate-grilling)",
            "Skill(mate-grill-with-docs)",
            "Skill(mate-domain-modeling)",
            "Skill(mate-simplify-code)",
            "Bash(openspec:*)",
            `Bash(${FRAMEWORK_NAME} cap graphify:*)`,
            `Bash(${path.join(depsWithDefaults.wrapperBinPath(), "openspec")}:*)`,
          ],
        },
      };
    },
    getInstallRequirements: (): InstallRequirement[] => [
      {
        id: "capability:openspec",
        label: "OpenSpec CLI",
        group: "companion",
        source: "OpenSpec capability",
        command: OPENSPEC_INSTALL_COMMAND,
        fingerprint: `openspec:${OPENSPEC_INSTALL_COMMAND}`,
        detect: () => depsWithDefaults.isCommandOnPath("openspec", depsWithDefaults.pathValue()),
        install: () =>
          depsWithDefaults.installCommand("npm", ["install", "-g", "@fission-ai/openspec@latest"]),
        verify: () => depsWithDefaults.isCommandOnPath("openspec", depsWithDefaults.pathValue()),
      },
    ],
    async apply(ctx) {
      const tools = deriveOpenSpecTools(ctx.activeProviders);
      if (ctx.mode === "setup" || tools.length > 0) {
        if (await ensureOpenSpecInstalled(ctx, depsWithDefaults)) {
          if (tools.length > 0) {
            await reconcileOpenSpecTools(ctx, depsWithDefaults.runCommand);
          }
        }
      }
      await reconcileOpenSpecSchema(ctx);
    },
    async teardown(ctx) {
      for (const tool of OPEN_SPEC_SUPPORTED_TOOLS) {
        await teardownToolRuntime(ctx.companionPath, tool);
      }
      await teardownOpenSpecSchema(ctx.companionPath);
    },
    forProvider: {
      claude: {
        // The archive-finish nudge hook ships in the bundled mate Claude
        // plugin and self-gates at runtime; openspec no longer contributes a
        // Claude hook file. Only legacy per-session nudge state is migrated.
        async apply(ctx: SetupContext) {
          const stateDir = path.join(ctx.companionPath, ".claude", "state");
          try {
            const entries = await fs.readdir(stateDir);
            await Promise.all(
              entries
                .filter((entry) => LEGACY_CLAUDE_STATE_PATTERN.test(entry))
                .map((entry) => fs.unlink(path.join(stateDir, entry))),
            );
            await pruneEmptyAncestors(stateDir, ctx.companionPath);
          } catch {
            /* no legacy state */
          }
        },
        async teardown(ctx: SetupContext) {
          await teardownToolRuntime(ctx.companionPath, "claude");
        },
      },
      opencode: {
        async apply() {},
        async teardown(ctx: SetupContext) {
          await teardownToolRuntime(ctx.companionPath, "opencode");
        },
      },
    },
  };
}

export const openspecPlugin = createOpenspecPlugin();
