import { CHANGE_PLACEHOLDER } from "../../selection";

export type WorkflowStepKind = "skill" | "completion" | "optional";

export interface WorkflowStep {
  kind: WorkflowStepKind;
  id: string;
  /** The action the stage performs. */
  what: string;
  /** The reason the stage is in the sequence at this position. */
  why: string;
  title: string;
  optional: boolean;
  step: number;
  prompt: string;
}

function stepPrompt(step: Omit<WorkflowStep, "prompt" | "step">): string {
  const change = CHANGE_PLACEHOLDER;
  switch (step.id) {
    case "grill":
      return `/grill-me or /interview-me for ${change} before exploring it.`;
    case "explore":
      return `/openspec-explore for ${change}.`;
    case "propose":
      return `/openspec-propose for ${change}; it creates the proposal, specs, design, and tasks.`;
    case "apply":
      return `/openspec-apply-change for ${change}.`;
    case "simplify":
      return `/mate-simplify-code for ${change}; preserve behavior and rerun the relevant tests.`;
    case "finish":
      return `/mate-artifact-finish for ${change}; run mate artifact finish "${change}" --json.`;
    default:
      return `Use ${step.title} for ${change}.`;
  }
}

function optionalStep(
  id: "grill" | "simplify",
  title: string,
  what: string,
  why: string,
): Omit<WorkflowStep, "prompt" | "step"> {
  return { kind: "optional", id, title, what, why, optional: true };
}

export function workflowSteps(): WorkflowStep[] {
  const unnumbered: Omit<WorkflowStep, "prompt" | "step">[] = [
    optionalStep(
      "grill",
      "grill / questionnaire",
      "Asks 3-5 high-leverage questions about the problem, scope, constraints, and acceptance criteria.",
      "Answering them here settles the assumptions while they still cost a conversation instead of a rewrite.",
    ),
    {
      kind: "skill",
      id: "explore",
      title: "openspec explore",
      what: "Explores the problem, scope, constraints, and intended outcome for the change.",
      why: "A proposal written before the problem is framed locks the wrong scope into the specs.",
      optional: false,
    },
    {
      kind: "skill",
      id: "propose",
      title: "openspec propose",
      what: "Creates the complete OpenSpec change: proposal, specs, design, and tasks.",
      why: "Writing the artifacts as one step keeps specs, design, and tasks agreeing before any code moves.",
      optional: false,
    },
    {
      kind: "skill",
      id: "apply",
      title: "openspec apply",
      what: "Implements the change by working through the tasks generated by the proposal.",
      why: "The tasks are the approved unit of work, so following them keeps the implementation inside the agreed scope.",
      optional: false,
    },
    optionalStep(
      "simplify",
      "mate simplify code",
      "Looks for smaller, clearer code once the tests pass, preserving behavior and rerunning the relevant tests.",
      "Cleanup lands before the specs are archived, so the shipped code and the recorded specs describe the same thing.",
    ),
    {
      kind: "completion",
      id: "finish",
      title: "mate artifact finish",
      what: "Archives the change and applies its delta specs to the main specs.",
      why: "It is the only sanctioned completion; a hand-committed finish leaves the main specs stale.",
      optional: false,
    },
  ];

  return unnumbered.map((step, index) => ({
    ...step,
    step: index + 1,
    prompt: stepPrompt(step),
  }));
}
